"""Replaceable boundaries. Hardware, storage and AI providers implement these ports."""

from datetime import datetime
from typing import Protocol

from .domain.models import CandidateRecord, ContextChanged, DeviceEvent, InboxItem, RecallCandidate, Template


class Repository(Protocol):
    def has_event(self, event_id: str) -> bool: ...
    def append_event(self, event: DeviceEvent, received_at: datetime) -> None: ...
    def get_template(self, template_id: str) -> Template: ...
    def create_inbox_item(self, item: InboxItem) -> None: ...
    def update_inbox_item(self, item: InboxItem) -> None: ...
    def save_candidate(self, candidate: CandidateRecord) -> None: ...
    def find_recall_candidates(self, context: ContextChanged) -> list[RecallCandidate]: ...
    def queue_recall(self, candidate: RecallCandidate, now: datetime) -> None: ...


class CameraPort(Protocol):
    def capture(self, inbox_item_id: str) -> str: ...


class AudioPort(Protocol):
    def record(self, inbox_item_id: str, max_seconds: int = 15) -> str: ...


class FeedbackPort(Protocol):
    def accepted(self) -> None: ...
    def partial(self) -> None: ...
    def recall_available(self) -> None: ...
    def error(self) -> None: ...


class StructuringPort(Protocol):
    def shape(self, template: Template, transcript: str, assets: list[dict[str, str]]) -> dict[str, object]: ...
